version: '3'
services:
  test:
    image: "akshat296/ubuntu-loaded:version3"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
      - "8080"
  
    tty: true
   
   
